export const majors = [
    'Africana Studies',
    'Ancient History',
    'Anthropology',
    'Architecture',
    'Biochemistry',
    'Biology',
    'Biophysics',
    'Chemistry',
    'Cinema Studies',
    'Classical Studies',
    'Cognitive Science',
    'Communication',
    'Comparative Literature',
    'Criminology',
    'Earth Science',
    'East Asian Area Studies',
    'East Asian Languages and Civilizations',
    'East Central European Studies',
    'Economics',
    'Engineering Major',
    'English',
    'Environmental Studies',
    'Fine Arts',
    'French Studies',
    'Gender, Sexuality and Women Studies',
    'Geology (see Earth Science)',
    'German',
    'Health and Societies',
    'Hispanic Studies',
    'History',
    'History of Art',
    'Individualized Major',
    'International Relations',
    'Italian Studies',
    'Jewish Studies',
    'Latin American and Latino Studies',
    'Linguistics',
    'Logic, Information and Computation',
    'Mathematical Economics',
    'Mathematics',
    'Modern Middle Eastern Studies',
    'Music',
    'Near Eastern Languages and Civilizations',
    'Neuroscience',
    'Philosophy',
    'Philosophy, Politics and Economics',
    'Physics',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Romance Languages',
    'Russian',
    'Science, Technology and Society',
    'Sociology',
    'South Asia Studies',
    'Spanish (see Hispanic Studies)',
    'Theatre Arts',
    'Urban Studies',
    'Visual Studies',
    'Bioengineering',
    'Chemical and Biomolecular Engineering',
    'Computer Engineering',
    'Computer Science',
    'Digital Media Design',
    'Electrical Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering and Applied Mechanics',
    'Networked and Social Systems Engineering',
    'Systems Science and Engineering',
    'Nursing',
    'Accounting',
    'Behavioral Economics',
    'Business Economics & Public Policy',
    'Environmental Policy & Management',
    'Finance',
    'Health Care Management and Policy',
    'Insurance & Risk Management',
    'Legal Studies & Business Ethics',
    'Marketing',
    'Marketing & Communication',
    'Marketing & Operations Management',
    'Operations & Information Management',
    'Real Estate',
    'Retailing',
    'Social Impact & Responsibility',
    'Statistics',
]

export const minors = [
    'Archaeological Science',
    'Law and Society',
    'Medical Sociology',
    'East Central European Studies',
    'Africana Studies',
    'Ancient History',
    'Anthropology',
    'Architecture',
    'Biochemistry',
    'Biology',
    'Biophysics',
    'Chemistry',
    'Cinema Studies',
    'Classical Studies',
    'Cognitive Science',
    'Communication',
    'Comparative Literature',
    'Criminology',
    'Earth Science',
    'East Asian Area Studies',
    'East Asian Languages and Civilizations',
    'East Central European Studies',
    'Economics',
    'Engineering Major',
    'English',
    'Environmental Studies',
    'Fine Arts',
    'French Studies',
    'Gender, Sexuality and Women Studies',
    'Geology (see Earth Science)',
    'German',
    'Health and Societies',
    'Hispanic Studies',
    'History',
    'History of Art',
    'Individualized Major',
    'International Relations',
    'Italian Studies',
    'Jewish Studies',
    'Latin American and Latino Studies',
    'Linguistics',
    'Logic, Information and Computation',
    'Mathematical Economics',
    'Mathematics',
    'Modern Middle Eastern Studies',
    'Music',
    'Near Eastern Languages and Civilizations',
    'Neuroscience',
    'Philosophy',
    'Philosophy, Politics and Economics',
    'Physics',
    'Political Science',
    'Psychology',
    'Religious Studies',
    'Romance Languages',
    'Russian',
    'Science, Technology and Society',
    'Sociology',
    'South Asia Studies',
    'Spanish (see Hispanic Studies)',
    'Theatre Arts',
    'Urban Studies',
    'Visual Studies',
    'Bioengineering',
    'Chemical and Biomolecular Engineering',
    'Computer Engineering',
    'Computer Science',
    'Digital Media Design',
    'Electrical Engineering',
    'Materials Science and Engineering',
    'Mechanical Engineering and Applied Mechanics',
    'Networked and Social Systems Engineering',
    'Systems Science and Engineering',
    'Nursing',
    'Accounting',
    'Behavioral Economics',
    'Business Economics & Public Policy',
    'Environmental Policy & Management',
    'Finance',
    'Health Care Management and Policy',
    'Insurance & Risk Management',
    'Legal Studies & Business Ethics',
    'Marketing',
    'Marketing & Communication',
    'Marketing & Operations Management',
    'Operations & Information Management',
    'Real Estate',
    'Retailing',
    'Social Impact & Responsibility',
    'Statistics',
]

export const schools = [
    'College of Arts and Sciences',
    'School of Engineering and Applied Science',
    'The Wharton School',
    'Nursing',
    'Management & Technology',
    'Huntsman',
    'Life Sciences and Management',
    'Nursing and Health Care Management',
    'Vajelos Integrated Program in Energy Research',
]
